// submittalCover.ts — fills the contractor's submittal cover template
// (src/assets/submittal-cover.pdf, an AcroForm PDF) entirely client-side with pdf-lib.
// Import this module DYNAMICALLY (like the xlsx parser) — pdf-lib rides in a lazy chunk.
//
// The template itself is generated by `scripts/build-submittal-template.mjs`; the field
// names and the geometry constants below are the contract between the two files.
//
// The template is one legal-size page with 63 named fields: header (To name,
// To Address, Date, RE:, Sent Via, SUMITTAL TITLE: [sic], Submittal number), the
// submittal-type checkboxes with their Rev fields, deviation/certification
// checkboxes (left unfilled — they belong to the reviewer), and an 11-row
// contents table: Spec / Arq Ref.(n) / item/Product(n) / QTY(n) /
// Manufacturer / Series(n).
//
// Selections beyond 11 items continue on sheets built from scratch (people read
// top-down and want full pages): a context line, the template's SUBMITTAL CONTENTS
// title + column band clipped from the pristine art, a full-page frame with 42 rows
// of NEW text fields (named "<column>(<row>)~p<page>" so they never collide with the
// template's), and the letterhead footer. Everything stays editable in Adobe.
import { PDFDocument, PDFForm, StandardFonts, rgb } from 'pdf-lib';

export interface CoverRow {
  ref: string;
  product: string;
  qty: string;
  mfr: string;
}

export interface CoverHeader {
  toName: string;
  toAddress: string;
  re: string;
  /** Already formatted for the PDF (MM/DD/YYYY). */
  date: string;
  sentVia: string;
  title: string;
  number: string;
  types: { productData: boolean; shopDrawings: boolean; samples: boolean; other: boolean };
  revs: { productData: string; shopDrawings: string; samples: string; other: string };
  otherText: string;
}

/** Rows on the cover sheet (the template's own table). Keep in sync with the modal. */
export const COVER_ROWS_PER_PAGE = 11;
/** Rows on each full-page continuation sheet. Keep in sync with the modal. */
export const CONT_ROWS_PER_PAGE = 42;

const TYPE_FIELDS: { key: keyof CoverHeader['types']; check: string; rev: string }[] = [
  { key: 'productData', check: 'Check Box1', rev: 'Rev(1)' },
  { key: 'shopDrawings', check: 'Check Box1(1)', rev: 'Rev(2)' },
  { key: 'samples', check: 'Check Box1(2)', rev: 'Rev(3)' },
  { key: 'other', check: 'Check Box1(3)', rev: 'Rev(4)' },
];

/* Continuation-sheet geometry, in template coordinates (612×1008 pt, origin bottom-
 * left, measured from the art): frame x 21..590 navy ~1.6pt; title + column band
 * occupy y 428..476; table columns Spec 23..102 / Item 102..425 / QTY 425..471 /
 * Mfr 471..589; row height 15; footer art below y=260.5. */
const NAVY = rgb(31 / 255, 56 / 255, 100 / 255);
const CONT_TOP = 950;
const HEADER_CLIP = { left: 19, bottom: 428, right: 590.5, top: 476 };
const HEADER_H = HEADER_CLIP.top - HEADER_CLIP.bottom;
const ROW_H = 15;
const FRAME_BOTTOM = CONT_TOP - HEADER_H - ROW_H * CONT_ROWS_PER_PAGE;
// Field-name bases for the rows created on continuation sheets. NO dots allowed:
// pdf-lib parses "." in createTextField names as field-hierarchy separators.
const COLS: { name: string; x: number; w: number }[] = [
  { name: 'Spec / Arq Ref', x: 23, w: 79 },
  { name: 'item/Product', x: 102, w: 323 },
  { name: 'QTY', x: 425, w: 46 },
  { name: 'Manufacturer / Series', x: 471, w: 118 },
];

function fillText(form: PDFForm, name: string, value: string) {
  if (value) form.getTextField(name).setText(value);
}

export async function generateSubmittalCover(templateBytes: ArrayBuffer, header: CoverHeader, rows: CoverRow[]): Promise<Uint8Array> {
  const pages: CoverRow[][] = [rows.slice(0, COVER_ROWS_PER_PAGE)];
  for (let i = COVER_ROWS_PER_PAGE; i < rows.length; i += CONT_ROWS_PER_PAGE) pages.push(rows.slice(i, i + CONT_ROWS_PER_PAGE));

  const main = await PDFDocument.load(templateBytes);
  const form = main.getForm();
  fillText(form, 'To name', header.toName);
  fillText(form, 'To Address', header.toAddress);
  fillText(form, 'RE:', header.re);
  fillText(form, 'Date', header.date);
  fillText(form, 'Sent Via', header.sentVia);
  fillText(form, 'SUMITTAL TITLE:', header.title);
  fillText(form, 'Submittal number', header.number);
  TYPE_FIELDS.forEach(({ key, check, rev }) => {
    if (!header.types[key]) return;
    form.getCheckBox(check).check();
    fillText(form, rev, header.revs[key]);
  });
  if (header.types.other) fillText(form, 'Other:', header.otherText);
  pages[0].forEach((r, i) => {
    const n = i + 1;
    fillText(form, `Spec / Arq Ref.(${n})`, r.ref);
    fillText(form, `item/Product(${n})`, r.product);
    fillText(form, `QTY(${n})`, r.qty);
    fillText(form, `Manufacturer / Series(${n})`, r.mfr);
  });

  if (pages.length > 1) {
    const artSrc = (await PDFDocument.load(templateBytes)).getPage(0);
    const { width, height } = artSrc.getSize();
    // The template's visible area is its CropBox ([0,216,612,1008] — letter-size
    // within a legal MediaBox); new pages must carry it or they show 216pt of dead
    // space below the footer and print at a different size than the cover.
    const crop = artSrc.getCropBox();
    const font = await main.embedFont(StandardFonts.HelveticaBold);
    // drawPage places the clip's lower-left corner at (x, y).
    const headerArt = await main.embedPage(artSrc, HEADER_CLIP);
    const footerArt = await main.embedPage(artSrc, { left: 0, bottom: 0, right: width, top: 260.5 });
    const contLabel = [header.number && `Submittal ${header.number}`, header.re].filter(Boolean).join(' — ');
    const vals = (r: CoverRow) => [r.ref, r.product, r.qty, r.mfr];

    for (let p = 1; p < pages.length; p++) {
      const pg = main.addPage([width, height]);
      pg.setCropBox(crop.x, crop.y, crop.width, crop.height);
      pg.drawText(`${contLabel ? contLabel + ' — ' : ''}continued (page ${p + 1} of ${pages.length})`, {
        x: 32, y: height - 40, size: 11, font, color: NAVY,
      });
      pg.drawRectangle({ x: 21, y: FRAME_BOTTOM, width: 569, height: CONT_TOP - FRAME_BOTTOM, borderColor: NAVY, borderWidth: 1.6 });
      pg.drawPage(headerArt, { x: HEADER_CLIP.left, y: CONT_TOP - HEADER_H });
      pg.drawPage(footerArt, { x: 0, y: 0 });
      const rowsTop = CONT_TOP - HEADER_H;
      for (let i = 0; i < CONT_ROWS_PER_PAGE; i++) {
        const r = pages[p][i];
        const y = rowsTop - ROW_H * (i + 1);
        COLS.forEach((c, ci) => {
          const fld = form.createTextField(`${c.name}(${i + 1})~p${p + 1}`);
          // Fresh fields have no /DA yet and setFontSize() throws — write it directly.
          fld.acroField.setDefaultAppearance('/Helv 9 Tf 0 g');
          const val = r ? vals(r)[ci] : '';
          if (val) fld.setText(val);
          fld.addToPage(pg, { x: c.x, y, width: c.w, height: ROW_H, borderWidth: 0.6, borderColor: rgb(0.4, 0.4, 0.4) });
        });
      }
    }
  }

  form.updateFieldAppearances();
  return main.save();
}

export function downloadPdf(bytes: Uint8Array, filename: string) {
  const buf = bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength) as ArrayBuffer;
  const blob = new Blob([buf], { type: 'application/pdf' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
